import os
import pg8000

DDL = [
    # Team
    """
    CREATE TABLE IF NOT EXISTS Team (
        TeamID   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        TeamName TEXT NOT NULL
    );
    """,
    # TeamAddress
    """
    CREATE TABLE IF NOT EXISTS TeamAddress (
        TeamAddressID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        TeamID INTEGER REFERENCES Team(TeamID),
        AddressLine TEXT,
        City TEXT,
        State TEXT,
        StartDate TEXT,
        EndDate TEXT DEFAULT '9999-12-31'
    );
    """,
    # Position
    """
    CREATE TABLE IF NOT EXISTS Position (
        PositionID TEXT PRIMARY KEY,
        FullName   TEXT
    );
    """,
    # Players
    """
    CREATE TABLE IF NOT EXISTS Players (
        PlayerID      TEXT PRIMARY KEY,
        FirstName     TEXT,
        MiddleInitial TEXT,
        LastName      TEXT,
        DOB           TEXT,
        Height        INTEGER,
        Weight        INTEGER
    );
    """,
    # Season
    """
    CREATE TABLE IF NOT EXISTS Season (
        SeasonID  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        Year      INTEGER UNIQUE,
        Name      TEXT,
        StartDate TEXT,
        EndDate   TEXT
    );
    """,
    # TeamRoster
    """
    CREATE TABLE IF NOT EXISTS TeamRoster (
        RosterID    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        TeamID      INTEGER REFERENCES Team(TeamID),
        PlayerID    TEXT    REFERENCES Players(PlayerID),
        SeasonID    INTEGER REFERENCES Season(SeasonID),
        PositionID  TEXT    REFERENCES Position(PositionID),
        StartDate   TEXT,
        EndDate     TEXT DEFAULT '9999-12-31',
        JerseyNumber TEXT
    );
    """,
    # Coach
    """
    CREATE TABLE IF NOT EXISTS Coach (
        CoachID   INTEGER PRIMARY KEY,
        FirstName TEXT,
        LastName  TEXT,
        DOB       TEXT,
        Phone     TEXT,
        Email     TEXT
    );
    """,
    # TeamCoach
    """
    CREATE TABLE IF NOT EXISTS TeamCoach (
        TeamCoachID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        CoachID     INTEGER REFERENCES Coach(CoachID),
        TeamID      INTEGER REFERENCES Team(TeamID),
        SeasonID    INTEGER REFERENCES Season(SeasonID),
        Title       TEXT,
        StartDate   TEXT,
        EndDate     TEXT DEFAULT '9999-12-31'
    );
    """,
    # Game (singular)
    """
    CREATE TABLE IF NOT EXISTS Game (
        GameID      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        SeasonID    INTEGER REFERENCES Season(SeasonID),
        GameDate    TEXT,
        WeekNumber  INTEGER,
        HomeTeamID  INTEGER REFERENCES Team(TeamID),
        AwayTeamID  INTEGER REFERENCES Team(TeamID),
        Location    TEXT,
        HomeScore   INTEGER,
        AwayScore   INTEGER
    );
    """,
    # StatAction
    """
    CREATE TABLE IF NOT EXISTS StatAction (
        StatActionID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        StatType     TEXT,
        ActionName   TEXT,
        Description  TEXT
    );
    """,
    # GamePlays
    """
    CREATE TABLE IF NOT EXISTS GamePlays (
        StatID        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        GameID        INTEGER REFERENCES Game(GameID),
        PlayNo        INTEGER,
        PlayerID      TEXT    REFERENCES Players(PlayerID),
        TeamID        INTEGER REFERENCES Team(TeamID),
        StatType      TEXT,
        StatActionID  INTEGER REFERENCES StatAction(StatActionID),
        Yards         TEXT,
        IsTD          BOOLEAN DEFAULT false,
        IsSafety      BOOLEAN DEFAULT false,
        SackWeight    NUMERIC(3,1) DEFAULT 1.0,
        SourceFileName TEXT,
        CreatedAt     timestamptz DEFAULT now(),
        Notes         TEXT
    );
    """,
    # Case-insensitive unique on TeamName
    """
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'idx_team_name_lower'
      ) THEN
        EXECUTE 'CREATE UNIQUE INDEX idx_team_name_lower ON Team (lower(TeamName))';
      END IF;
    END$$;
    """,
    # Additional indexes (IF NOT EXISTS is supported)
    "CREATE INDEX IF NOT EXISTS idx_team_teamID ON Team(TeamID);",
    "CREATE INDEX IF NOT EXISTS idx_teamaddress_teamID ON TeamAddress(TeamID);",
    "CREATE INDEX IF NOT EXISTS idx_teamroster_teamID ON TeamRoster(TeamID);",
    "CREATE INDEX IF NOT EXISTS idx_teamroster_playerID ON TeamRoster(PlayerID);",
    "CREATE INDEX IF NOT EXISTS idx_teamroster_seasonID ON TeamRoster(SeasonID);",
    "CREATE INDEX IF NOT EXISTS idx_game_homeTeamID ON Game(HomeTeamID);",
    "CREATE INDEX IF NOT EXISTS idx_game_awayTeamID ON Game(AwayTeamID);",
    "CREATE INDEX IF NOT EXISTS idx_game_seasonID ON Game(SeasonID);",
    "CREATE INDEX IF NOT EXISTS idx_gameplays_gameID ON GamePlays(GameID);",
    "CREATE INDEX IF NOT EXISTS idx_gameplays_playerID ON GamePlays(PlayerID);",
    "CREATE INDEX IF NOT EXISTS idx_gameplays_teamID ON GamePlays(TeamID);",
    "CREATE INDEX IF NOT EXISTS idx_gameplays_statActionID ON GamePlays(StatActionID);",
    "CREATE INDEX IF NOT EXISTS idx_stataction_stattype ON StatAction(StatType);",
    "CREATE INDEX IF NOT EXISTS idx_teamcoach_teamID ON TeamCoach(TeamID);",
    "CREATE INDEX IF NOT EXISTS idx_teamcoach_coachID ON TeamCoach(CoachID);",
    "CREATE INDEX IF NOT EXISTS idx_teamcoach_seasonID ON TeamCoach(SeasonID);",
]

SEED_POSITIONS = [
    ('QB', 'Quarterback'), ('RB', 'Running Back'), ('WR', 'Wide Receiver'),
    ('TE', 'Tight End'), ('OT', 'Offensive Tackle'), ('OG', 'Offensive Guard'),
    ('C', 'Center'), ('OL', 'Offensive Lineman'), ('LB', 'Linebacker'),
    ('DL', 'Defensive Lineman'), ('DT', 'Defensive Tackle'), ('EDGE', 'Edge Defender'),
    ('CB', 'Cornerback'), ('S', 'Safety'), ('K', 'Kicker'),
    ('P', 'Punter'), ('LS', 'Long Snapper')
]

SEED_STATACTIONS = [
    (1, 'Offense', 'Pass Incomplete', 'Player attempted a pass'),
    (2, 'Offense', 'Pass Complete', 'Player completed a pass'),
    (3, 'Offense', 'Pass Target', 'Player was targeted for a pass'),
    (4, 'Offense', 'Catch', 'Player caught a pass'),
    (5, 'Offense', 'Rush', 'Player ran the ball'),
    (6, 'Offense', 'Fumble', 'Player fumbled'),
    (7, 'Offense', 'Fumble Recovery', 'Recovered a fumble'),
    (8, 'Defense', 'Tackle', 'Solo tackle'),
    (9, 'Defense', 'Tackle Assist', 'Assisted a tackle'),
    (10, 'Defense', 'Sack', 'Quarterback sack'),
    (22, 'Defense', 'Sack Assist', 'Quarterback sack (assisted)'),
    (11, 'Defense', 'Forced Fumble', 'Caused a fumble'),
    (12, 'Defense', 'Fumble Recovery', 'Recovered a fumble'),
    (13, 'Defense', 'Interception', 'Intercepted a pass'),
    (14, 'Defense', 'Deflection', 'Deflected a pass'),
    (15, 'Special Teams', 'Field Goal Attempt', 'Kicked a field goal'),
    (16, 'Special Teams', 'Field Goal Made', 'Made a field goal'),
    (17, 'Special Teams', 'PAT Attempt', 'Kicked a point after touchdown'),
    (18, 'Special Teams', 'PAT Made', 'Made a PAT'),
    (19, 'Special Teams', 'Punt', 'Punted the ball'),
    (20, 'Special Teams', 'Kick Return', 'Returned a kickoff'),
    (21, 'Special Teams', 'Punt Return', 'Returned a punt')
]

def run_statements(cur, statements):
    for stmt in statements:
        cur.execute(stmt)

def lambda_handler(event, context):
    conn = pg8000.connect(
        host=os.environ["DB_HOST"],
        database=os.environ["DB_NAME"],
        user=os.environ["DB_USER"],
        password=os.environ["DB_PASS"],
        port=int(os.environ.get("DB_PORT", "5432"))
    )
    try:
        with conn.cursor() as cur:
            # Tables and indexes
            run_statements(cur, DDL)

            # Seeds
            cur.executemany(
                "INSERT INTO Position (PositionID, FullName) VALUES (%s, %s) "
                "ON CONFLICT (PositionID) DO NOTHING",
                SEED_POSITIONS
            )
            cur.executemany(
                "INSERT INTO StatAction (StatActionID, StatType, ActionName, Description) "
                "VALUES (%s, %s, %s, %s) "
                "ON CONFLICT (StatActionID) DO NOTHING",
                SEED_STATACTIONS
            )
        conn.commit()
        return {"ok": True, "created_or_verified": "tables,indexes,seeds"}
    finally:
        conn.close()
